<?php

	$role_info[395] = array (
  'code' => 'goal-content',
  'name' => 
  array (
    'ar' => 'إدارة المحتوى',
    'en' => 'arole.395',
  ),
  'menu' => 
  array (
    'need_admin' => false,
    'id' => '395',
    'menu_name_' => 'إدارة المحتوى',
    'menu_name_ar' => 'إدارة المحتوى',
    'menu_name_en' => 'arole.395',
    'page' => 'main.php?Main_Page=fm.php&a=1283&r=395',
    'css' => 'info',
    'icon' => ' icon-395',
    'showme' => true,
    'items' => 
    array (
      104961 => 
      array (
        'id' => '104961',
        'code' => 'f2-a-workflow_file/qsearch',
        'level' => '1',
        'menu_name_ar' => 'الملفات',
        'menu_name_en' => 'Files',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowFile&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104961 bfc-',
      ),
      105030 => 
      array (
        'id' => '105030',
        'code' => 'f2-a-content_item/qsearch',
        'level' => '1',
        'menu_name_ar' => 'عناصر المحتوى',
        'menu_name_en' => 'Content items',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ContentItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105030 bfc-',
      ),
      105027 => 
      array (
        'id' => '105027',
        'code' => 'f2-a-content/qsearch',
        'level' => '1',
        'menu_name_ar' => 'محتويات',
        'menu_name_en' => 'contents',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Content&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105027 bfc-',
      ),
      105014 => 
      array (
        'id' => '105014',
        'code' => 'f2-a-publication/qsearch',
        'level' => '1',
        'menu_name_ar' => 'المقالات',
        'menu_name_en' => 'Publications',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Publication&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105014 bfc-',
      ),
      105031 => 
      array (
        'id' => '105031',
        'code' => 'f2-a-intelligent_content/qsearch',
        'level' => '1',
        'menu_name_ar' => 'المحتويات الذكية',
        'menu_name_en' => 'intelligent content',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=IntelligentContent&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105031 bfc-',
      ),
      105026 => 
      array (
        'id' => '105026',
        'code' => 'f2-a-page/qsearch',
        'level' => '1',
        'menu_name_ar' => 'الصفحات',
        'menu_name_en' => 'pages',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Page&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105026 bfc-',
      ),
      105032 => 
      array (
        'id' => '105032',
        'code' => 'f2-a-page_theme/qsearch',
        'level' => '1',
        'menu_name_ar' => 'الثيمات',
        'menu_name_en' => 'Page themes',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=PageTheme&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105032 bfc-',
      ),
      105029 => 
      array (
        'id' => '105029',
        'code' => 'f2-a-page_item/qsearch',
        'level' => '1',
        'menu_name_ar' => 'عناصر الصفحات',
        'menu_name_en' => 'Page items',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=PageItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105029 bfc-',
      ),
      105028 => 
      array (
        'id' => '105028',
        'code' => 'f2-a-page_section/qsearch',
        'level' => '1',
        'menu_name_ar' => 'أقسام الصفحات',
        'menu_name_en' => 'page sections',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=PageSection&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105028 bfc-',
      ),
      105021 => 
      array (
        'id' => '105021',
        'code' => 'f2-a-section_template/qsearch',
        'level' => '1',
        'menu_name_ar' => 'نماذج',
        'menu_name_en' => 'templates',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=SectionTemplate&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105021 bfc-',
      ),
    ),
    'otherbfs' => 
    array (
      104956 => 
      array (
        'id' => '104956',
        'code' => 'f2-a-workflow_file/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء ملف',
        'menu_name_en' => 'create File',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=WorkflowFile&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104956 bfc-',
      ),
      104958 => 
      array (
        'id' => '104958',
        'code' => 'f2-a-workflow_file/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح ملف',
        'menu_name_en' => 'delete File',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=WorkflowFile&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104958 bfc-',
      ),
      104959 => 
      array (
        'id' => '104959',
        'code' => 'f2-a-workflow_file/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل ملف',
        'menu_name_en' => 'display details of File',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=WorkflowFile&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104959 bfc-',
      ),
      104960 => 
      array (
        'id' => '104960',
        'code' => 'f2-a-workflow_file/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في الملفات',
        'menu_name_en' => 'Files search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=WorkflowFile&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104960 bfc-',
      ),
      104961 => 
      array (
        'id' => '104961',
        'code' => 'f2-a-workflow_file/qsearch',
        'level' => '1',
        'menu_name_ar' => 'الملفات',
        'menu_name_en' => 'Files',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowFile&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104961 bfc-',
      ),
      104963 => 
      array (
        'id' => '104963',
        'code' => 'f2-a-content/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل محتوى',
        'menu_name_en' => 'display details of content',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Content&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104963 bfc-',
      ),
      104964 => 
      array (
        'id' => '104964',
        'code' => 'f2-a-content/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في محتويات',
        'menu_name_en' => 'contents search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Content&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104964 bfc-',
      ),
      104966 => 
      array (
        'id' => '104966',
        'code' => 'f2-a-content/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء محتوى',
        'menu_name_en' => 'create content',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Content&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104966 bfc-',
      ),
      104969 => 
      array (
        'id' => '104969',
        'code' => 'f2-a-content/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح محتوى',
        'menu_name_en' => 'delete content',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Content&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104969 bfc-',
      ),
      104970 => 
      array (
        'id' => '104970',
        'code' => 'f2-a-content_item/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل عنصر محتوى',
        'menu_name_en' => 'display details of Content item',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=ContentItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104970 bfc-',
      ),
      104971 => 
      array (
        'id' => '104971',
        'code' => 'f2-a-content_item/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في عناصر المحتوى',
        'menu_name_en' => 'Content items search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=ContentItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104971 bfc-',
      ),
      104973 => 
      array (
        'id' => '104973',
        'code' => 'f2-a-content_item/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء عنصر محتوى',
        'menu_name_en' => 'create Content item',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=ContentItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104973 bfc-',
      ),
      104976 => 
      array (
        'id' => '104976',
        'code' => 'f2-a-content_item/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح عنصر محتوى',
        'menu_name_en' => 'delete Content item',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=ContentItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104976 bfc-',
      ),
      104977 => 
      array (
        'id' => '104977',
        'code' => 'f2-a-intelligent_content/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل محتوى ذكي',
        'menu_name_en' => 'display details of Intelligent content',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=IntelligentContent&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104977 bfc-',
      ),
      104978 => 
      array (
        'id' => '104978',
        'code' => 'f2-a-intelligent_content/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في المحتويات الذكية',
        'menu_name_en' => 'intelligent content search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=IntelligentContent&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104978 bfc-',
      ),
      104980 => 
      array (
        'id' => '104980',
        'code' => 'f2-a-intelligent_content/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء محتوى ذكي',
        'menu_name_en' => 'create Intelligent content',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=IntelligentContent&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104980 bfc-',
      ),
      104983 => 
      array (
        'id' => '104983',
        'code' => 'f2-a-intelligent_content/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح محتوى ذكي',
        'menu_name_en' => 'delete Intelligent content',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=IntelligentContent&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104983 bfc-',
      ),
      104984 => 
      array (
        'id' => '104984',
        'code' => 'f2-a-page/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل صفحة',
        'menu_name_en' => 'display details of page',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Page&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104984 bfc-',
      ),
      104985 => 
      array (
        'id' => '104985',
        'code' => 'f2-a-page/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في الصفحات',
        'menu_name_en' => 'pages search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Page&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104985 bfc-',
      ),
      104987 => 
      array (
        'id' => '104987',
        'code' => 'f2-a-page/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء صفحة',
        'menu_name_en' => 'create page',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Page&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104987 bfc-',
      ),
      104990 => 
      array (
        'id' => '104990',
        'code' => 'f2-a-page/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح صفحة',
        'menu_name_en' => 'delete page',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Page&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104990 bfc-',
      ),
      104991 => 
      array (
        'id' => '104991',
        'code' => 'f2-a-page_item/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل عنصر صفحة',
        'menu_name_en' => 'display details of Page item',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=PageItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104991 bfc-',
      ),
      104992 => 
      array (
        'id' => '104992',
        'code' => 'f2-a-page_item/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في عناصر الصفحات',
        'menu_name_en' => 'Page items search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=PageItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104992 bfc-',
      ),
      104994 => 
      array (
        'id' => '104994',
        'code' => 'f2-a-page_item/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء عنصر صفحة',
        'menu_name_en' => 'create Page item',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=PageItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104994 bfc-',
      ),
      104997 => 
      array (
        'id' => '104997',
        'code' => 'f2-a-page_item/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح عنصر صفحة',
        'menu_name_en' => 'delete Page item',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=PageItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104997 bfc-',
      ),
      104998 => 
      array (
        'id' => '104998',
        'code' => 'f2-a-page_section/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل قسم صفحة',
        'menu_name_en' => 'display details of page section',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=PageSection&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104998 bfc-',
      ),
      104999 => 
      array (
        'id' => '104999',
        'code' => 'f2-a-page_section/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في أقسام الصفحات',
        'menu_name_en' => 'page sections search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=PageSection&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-104999 bfc-',
      ),
      105001 => 
      array (
        'id' => '105001',
        'code' => 'f2-a-page_section/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء قسم صفحة',
        'menu_name_en' => 'create page section',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=PageSection&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105001 bfc-',
      ),
      105004 => 
      array (
        'id' => '105004',
        'code' => 'f2-a-page_section/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح قسم صفحة',
        'menu_name_en' => 'delete page section',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=PageSection&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105004 bfc-',
      ),
      105005 => 
      array (
        'id' => '105005',
        'code' => 'f2-a-page_theme/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل ثيم',
        'menu_name_en' => 'display details of Page theme',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=PageTheme&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105005 bfc-',
      ),
      105006 => 
      array (
        'id' => '105006',
        'code' => 'f2-a-page_theme/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في الثيمات',
        'menu_name_en' => 'Page themes search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=PageTheme&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105006 bfc-',
      ),
      105008 => 
      array (
        'id' => '105008',
        'code' => 'f2-a-page_theme/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء ثيم',
        'menu_name_en' => 'create Page theme',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=PageTheme&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105008 bfc-',
      ),
      105011 => 
      array (
        'id' => '105011',
        'code' => 'f2-a-page_theme/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح ثيم',
        'menu_name_en' => 'delete Page theme',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=PageTheme&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105011 bfc-',
      ),
      105012 => 
      array (
        'id' => '105012',
        'code' => 'f2-a-publication/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل مقال',
        'menu_name_en' => 'display details of Publication',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=Publication&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105012 bfc-',
      ),
      105013 => 
      array (
        'id' => '105013',
        'code' => 'f2-a-publication/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في المقالات',
        'menu_name_en' => 'Publications search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=Publication&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105013 bfc-',
      ),
      105014 => 
      array (
        'id' => '105014',
        'code' => 'f2-a-publication/qsearch',
        'level' => '1',
        'menu_name_ar' => 'المقالات',
        'menu_name_en' => 'Publications',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Publication&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105014 bfc-',
      ),
      105015 => 
      array (
        'id' => '105015',
        'code' => 'f2-a-publication/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء مقال',
        'menu_name_en' => 'create Publication',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=Publication&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105015 bfc-',
      ),
      105018 => 
      array (
        'id' => '105018',
        'code' => 'f2-a-publication/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح مقال',
        'menu_name_en' => 'delete Publication',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=Publication&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105018 bfc-',
      ),
      105019 => 
      array (
        'id' => '105019',
        'code' => 'f2-a-section_template/display',
        'level' => '1',
        'menu_name_ar' => 'عرض تفاصيل نموذج',
        'menu_name_en' => 'display details of template',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=SectionTemplate&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105019 bfc-',
      ),
      105020 => 
      array (
        'id' => '105020',
        'code' => 'f2-a-section_template/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في نماذج',
        'menu_name_en' => 'templates search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=SectionTemplate&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105020 bfc-',
      ),
      105021 => 
      array (
        'id' => '105021',
        'code' => 'f2-a-section_template/qsearch',
        'level' => '1',
        'menu_name_ar' => 'نماذج',
        'menu_name_en' => 'templates',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=SectionTemplate&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105021 bfc-',
      ),
      105022 => 
      array (
        'id' => '105022',
        'code' => 'f2-a-section_template/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء نموذج',
        'menu_name_en' => 'create template',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=SectionTemplate&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105022 bfc-',
      ),
      105025 => 
      array (
        'id' => '105025',
        'code' => 'f2-a-section_template/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح نموذج',
        'menu_name_en' => 'delete template',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=SectionTemplate&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105025 bfc-',
      ),
      105026 => 
      array (
        'id' => '105026',
        'code' => 'f2-a-page/qsearch',
        'level' => '1',
        'menu_name_ar' => 'الصفحات',
        'menu_name_en' => 'pages',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Page&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105026 bfc-',
      ),
      105027 => 
      array (
        'id' => '105027',
        'code' => 'f2-a-content/qsearch',
        'level' => '1',
        'menu_name_ar' => 'محتويات',
        'menu_name_en' => 'contents',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=Content&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105027 bfc-',
      ),
      105028 => 
      array (
        'id' => '105028',
        'code' => 'f2-a-page_section/qsearch',
        'level' => '1',
        'menu_name_ar' => 'أقسام الصفحات',
        'menu_name_en' => 'page sections',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=PageSection&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105028 bfc-',
      ),
      105029 => 
      array (
        'id' => '105029',
        'code' => 'f2-a-page_item/qsearch',
        'level' => '1',
        'menu_name_ar' => 'عناصر الصفحات',
        'menu_name_en' => 'Page items',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=PageItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105029 bfc-',
      ),
      105030 => 
      array (
        'id' => '105030',
        'code' => 'f2-a-content_item/qsearch',
        'level' => '1',
        'menu_name_ar' => 'عناصر المحتوى',
        'menu_name_en' => 'Content items',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=ContentItem&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105030 bfc-',
      ),
      105031 => 
      array (
        'id' => '105031',
        'code' => 'f2-a-intelligent_content/qsearch',
        'level' => '1',
        'menu_name_ar' => 'المحتويات الذكية',
        'menu_name_en' => 'intelligent content',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=IntelligentContent&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105031 bfc-',
      ),
      105032 => 
      array (
        'id' => '105032',
        'code' => 'f2-a-page_theme/qsearch',
        'level' => '1',
        'menu_name_ar' => 'الثيمات',
        'menu_name_en' => 'Page themes',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=PageTheme&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105032 bfc-',
      ),
    ),
    'sub-folders' => 
    array (
    ),
  ),
);