<?php

$role_info[393] = array(
  'code' => 'goal-WORK-ORG',
  'name' =>
  array(
    'ar' => 'تنظيم العمل',
    'en' => 'work organization',
  ),
  'menu' =>
  array(
    'need_admin' => false,
    'id' => '393',
    'menu_name_' => 'تنظيم العمل',
    'menu_name_ar' => 'تنظيم العمل',
    'menu_name_en' => 'work organization',
    'page' => 'main.php?Main_Page=fm.php&a=1283&r=393',
    'css' => 'info',
    'icon' => ' icon-393',
    'showme' => true,
    'items' =>
    array(
      105038 =>
      array(
        'id' => '105038',
        'code' => 'f2-a-workflow_commitee_member/qsearch',
        'level' => '999',
        'menu_name_ar' => 'أعضاء اللجان',
        'menu_name_en' => 'Workflow commitee members',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowCommiteeMember&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105038 bfc-',
      ),
      105199 =>
      array(
        'id' => '105199',
        'code' => 'f2-a-workflow_commitee/qsearch',
        'level' => '999',
        'menu_name_ar' => 'اللجان',
        'menu_name_en' => 'Workflow commitees',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowCommitee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105199 bfc-',
      ),
      105045 =>
      array(
        'id' => '105045',
        'code' => 'f2-a-workflow_employee/qsearch',
        'level' => '999',
        'menu_name_ar' => 'موظفي إدارة أعمال',
        'menu_name_en' => 'Workflow employees',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowEmployee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105045 bfc-',
      ),
      105206 =>
      array(
        'id' => '105206',
        'code' => 'f2-a-workflow_model/qsearch',
        'level' => '999',
        'menu_name_ar' => 'نماذج سير العمل',
        'menu_name_en' => 'Workflow models',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowModel&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105206 bfc-',
      ),
      105220 =>
      array(
        'id' => '105220',
        'code' => 'f2-a-workflow_stage/qsearch',
        'level' => '999',
        'menu_name_ar' => 'المراحل',
        'menu_name_en' => 'Workflow stages',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowStage&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105220 bfc-',
      ),
      105227 =>
      array(
        'id' => '105227',
        'code' => 'f2-a-workflow_task/qsearch',
        'level' => '999',
        'menu_name_ar' => 'workflow_task',
        'menu_name_en' => 'Workflow tasks',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowTask&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105227 bfc-',
      ),
      105213 =>
      array(
        'id' => '105213',
        'code' => 'f2-a-workflow_scope/qsearch',
        'level' => '999',
        'menu_name_ar' => 'البرامج',
        'menu_name_en' => 'Workflow scopes',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowScope&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105213 bfc-',
      ),
      105192 =>
      array(
        'id' => '105192',
        'code' => 'f2-a-workflow_action/qsearch',
        'level' => '999',
        'menu_name_ar' => 'إجراءات',
        'menu_name_en' => 'Workflow actions',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowAction&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105192 bfc-',
      ),
      105241 =>
      array(
        'id' => '105241',
        'code' => 'f2-a-workflow_transition/qsearch',
        'level' => '999',
        'menu_name_ar' => 'التحولات',
        'menu_name_en' => 'transitions',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowTransition&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105241 bfc-',
      ),
    ),
    'otherbfs' =>
    array(
      105033 =>
      array(
        'id' => '105033',
        'code' => 'f2-a-workflow_commitee_member/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء عضو لجنة',
        'menu_name_en' => 'create Workflow commitee member',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=WorkflowCommiteeMember&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105033 bfc-',
      ),
      105034 =>
      array(
        'id' => '105034',
        'code' => 'f2-a-workflow_commitee_member/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة أعضاء اللجان',
        'menu_name_en' => 'Workflow commitee members administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=WorkflowCommiteeMember&currmod=workflow&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105034 bfc-',
      ),
      105035 =>
      array(
        'id' => '105035',
        'code' => 'f2-a-workflow_commitee_member/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح عضو لجنة',
        'menu_name_en' => 'delete Workflow commitee member',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=WorkflowCommiteeMember&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105035 bfc-',
      ),
      105036 =>
      array(
        'id' => '105036',
        'code' => 'f2-a-workflow_commitee_member/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل عضو لجنة',
        'menu_name_en' => 'display details of Workflow commitee member',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=WorkflowCommiteeMember&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105036 bfc-',
      ),
      105037 =>
      array(
        'id' => '105037',
        'code' => 'f2-a-workflow_commitee_member/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في أعضاء اللجان',
        'menu_name_en' => 'Workflow commitee members search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=WorkflowCommiteeMember&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105037 bfc-',
      ),
      105038 =>
      array(
        'id' => '105038',
        'code' => 'f2-a-workflow_commitee_member/qsearch',
        'level' => '999',
        'menu_name_ar' => 'أعضاء اللجان',
        'menu_name_en' => 'Workflow commitee members',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowCommiteeMember&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105038 bfc-',
      ),
      105040 =>
      array(
        'id' => '105040',
        'code' => 'f2-a-workflow_employee/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء موظف',
        'menu_name_en' => 'create Workflow employee',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=WorkflowEmployee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105040 bfc-',
      ),
      105041 =>
      array(
        'id' => '105041',
        'code' => 'f2-a-workflow_employee/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة موظفي إدارة أعمال',
        'menu_name_en' => 'Workflow employees administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=WorkflowEmployee&currmod=workflow&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105041 bfc-',
      ),
      105042 =>
      array(
        'id' => '105042',
        'code' => 'f2-a-workflow_employee/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح موظف',
        'menu_name_en' => 'delete Workflow employee',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=WorkflowEmployee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105042 bfc-',
      ),
      105043 =>
      array(
        'id' => '105043',
        'code' => 'f2-a-workflow_employee/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل موظف',
        'menu_name_en' => 'display details of Workflow employee',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=WorkflowEmployee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105043 bfc-',
      ),
      105044 =>
      array(
        'id' => '105044',
        'code' => 'f2-a-workflow_employee/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في موظفي إدارة أعمال',
        'menu_name_en' => 'Workflow employees search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=WorkflowEmployee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105044 bfc-',
      ),
      105045 =>
      array(
        'id' => '105045',
        'code' => 'f2-a-workflow_employee/qsearch',
        'level' => '999',
        'menu_name_ar' => 'موظفي إدارة أعمال',
        'menu_name_en' => 'Workflow employees',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowEmployee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105045 bfc-',
      ),
      105187 =>
      array(
        'id' => '105187',
        'code' => 'f2-a-workflow_action/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء إجراء',
        'menu_name_en' => 'create Workflow action',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=WorkflowAction&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105187 bfc-',
      ),
      105188 =>
      array(
        'id' => '105188',
        'code' => 'f2-a-workflow_action/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة إجراءات',
        'menu_name_en' => 'Workflow actions administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=WorkflowAction&currmod=workflow&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105188 bfc-',
      ),
      105189 =>
      array(
        'id' => '105189',
        'code' => 'f2-a-workflow_action/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح إجراء',
        'menu_name_en' => 'delete Workflow action',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=WorkflowAction&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105189 bfc-',
      ),
      105190 =>
      array(
        'id' => '105190',
        'code' => 'f2-a-workflow_action/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل إجراء',
        'menu_name_en' => 'display details of Workflow action',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=WorkflowAction&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105190 bfc-',
      ),
      105191 =>
      array(
        'id' => '105191',
        'code' => 'f2-a-workflow_action/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في إجراءات',
        'menu_name_en' => 'Workflow actions search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=WorkflowAction&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105191 bfc-',
      ),
      105192 =>
      array(
        'id' => '105192',
        'code' => 'f2-a-workflow_action/qsearch',
        'level' => '999',
        'menu_name_ar' => 'إجراءات',
        'menu_name_en' => 'Workflow actions',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowAction&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105192 bfc-',
      ),
      105194 =>
      array(
        'id' => '105194',
        'code' => 'f2-a-workflow_commitee/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء لجنة',
        'menu_name_en' => 'create Workflow commitee',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=WorkflowCommitee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105194 bfc-',
      ),
      105195 =>
      array(
        'id' => '105195',
        'code' => 'f2-a-workflow_commitee/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة اللجان',
        'menu_name_en' => 'Workflow commitees administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=WorkflowCommitee&currmod=workflow&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105195 bfc-',
      ),
      105196 =>
      array(
        'id' => '105196',
        'code' => 'f2-a-workflow_commitee/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح لجنة',
        'menu_name_en' => 'delete Workflow commitee',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=WorkflowCommitee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105196 bfc-',
      ),
      105197 =>
      array(
        'id' => '105197',
        'code' => 'f2-a-workflow_commitee/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل لجنة',
        'menu_name_en' => 'display details of Workflow commitee',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=WorkflowCommitee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105197 bfc-',
      ),
      105198 =>
      array(
        'id' => '105198',
        'code' => 'f2-a-workflow_commitee/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في اللجان',
        'menu_name_en' => 'Workflow commitees search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=WorkflowCommitee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105198 bfc-',
      ),
      105199 =>
      array(
        'id' => '105199',
        'code' => 'f2-a-workflow_commitee/qsearch',
        'level' => '999',
        'menu_name_ar' => 'اللجان',
        'menu_name_en' => 'Workflow commitees',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowCommitee&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105199 bfc-',
      ),
      105201 =>
      array(
        'id' => '105201',
        'code' => 'f2-a-workflow_model/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء نموذج سير عمل',
        'menu_name_en' => 'create Workflow model',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=WorkflowModel&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105201 bfc-',
      ),
      105202 =>
      array(
        'id' => '105202',
        'code' => 'f2-a-workflow_model/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة نماذج سير العمل',
        'menu_name_en' => 'Workflow models administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=WorkflowModel&currmod=workflow&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105202 bfc-',
      ),
      105203 =>
      array(
        'id' => '105203',
        'code' => 'f2-a-workflow_model/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح نموذج سير عمل',
        'menu_name_en' => 'delete Workflow model',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=WorkflowModel&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105203 bfc-',
      ),
      105204 =>
      array(
        'id' => '105204',
        'code' => 'f2-a-workflow_model/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل نموذج سير عمل',
        'menu_name_en' => 'display details of Workflow model',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=WorkflowModel&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105204 bfc-',
      ),
      105205 =>
      array(
        'id' => '105205',
        'code' => 'f2-a-workflow_model/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في نماذج سير العمل',
        'menu_name_en' => 'Workflow models search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=WorkflowModel&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105205 bfc-',
      ),
      105206 =>
      array(
        'id' => '105206',
        'code' => 'f2-a-workflow_model/qsearch',
        'level' => '999',
        'menu_name_ar' => 'نماذج سير العمل',
        'menu_name_en' => 'Workflow models',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowModel&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105206 bfc-',
      ),
      105208 =>
      array(
        'id' => '105208',
        'code' => 'f2-a-workflow_scope/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء برنامج',
        'menu_name_en' => 'create Workflow scope',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=WorkflowScope&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105208 bfc-',
      ),
      105209 =>
      array(
        'id' => '105209',
        'code' => 'f2-a-workflow_scope/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة البرامج',
        'menu_name_en' => 'Workflow scopes administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=WorkflowScope&currmod=workflow&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105209 bfc-',
      ),
      105210 =>
      array(
        'id' => '105210',
        'code' => 'f2-a-workflow_scope/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح برنامج',
        'menu_name_en' => 'delete Workflow scope',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=WorkflowScope&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105210 bfc-',
      ),
      105211 =>
      array(
        'id' => '105211',
        'code' => 'f2-a-workflow_scope/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل برنامج',
        'menu_name_en' => 'display details of Workflow scope',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=WorkflowScope&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105211 bfc-',
      ),
      105212 =>
      array(
        'id' => '105212',
        'code' => 'f2-a-workflow_scope/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في البرامج',
        'menu_name_en' => 'Workflow scopes search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=WorkflowScope&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105212 bfc-',
      ),
      105213 =>
      array(
        'id' => '105213',
        'code' => 'f2-a-workflow_scope/qsearch',
        'level' => '999',
        'menu_name_ar' => 'البرامج',
        'menu_name_en' => 'Workflow scopes',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowScope&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105213 bfc-',
      ),
      105215 =>
      array(
        'id' => '105215',
        'code' => 'f2-a-workflow_stage/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء مرحلة',
        'menu_name_en' => 'create Workflow stage',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=WorkflowStage&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105215 bfc-',
      ),
      105216 =>
      array(
        'id' => '105216',
        'code' => 'f2-a-workflow_stage/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة المراحل',
        'menu_name_en' => 'Workflow stages administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=WorkflowStage&currmod=workflow&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105216 bfc-',
      ),
      105217 =>
      array(
        'id' => '105217',
        'code' => 'f2-a-workflow_stage/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح مرحلة',
        'menu_name_en' => 'delete Workflow stage',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=WorkflowStage&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105217 bfc-',
      ),
      105218 =>
      array(
        'id' => '105218',
        'code' => 'f2-a-workflow_stage/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل مرحلة',
        'menu_name_en' => 'display details of Workflow stage',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=WorkflowStage&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105218 bfc-',
      ),
      105219 =>
      array(
        'id' => '105219',
        'code' => 'f2-a-workflow_stage/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في المراحل',
        'menu_name_en' => 'Workflow stages search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=WorkflowStage&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105219 bfc-',
      ),
      105220 =>
      array(
        'id' => '105220',
        'code' => 'f2-a-workflow_stage/qsearch',
        'level' => '999',
        'menu_name_ar' => 'المراحل',
        'menu_name_en' => 'Workflow stages',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowStage&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105220 bfc-',
      ),
      105222 =>
      array(
        'id' => '105222',
        'code' => 'f2-a-workflow_task/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء',
        'menu_name_en' => 'create Workflow task',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=WorkflowTask&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105222 bfc-',
      ),
      105223 =>
      array(
        'id' => '105223',
        'code' => 'f2-a-workflow_task/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة workflow_task',
        'menu_name_en' => 'Workflow tasks administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=WorkflowTask&currmod=workflow&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105223 bfc-',
      ),
      105224 =>
      array(
        'id' => '105224',
        'code' => 'f2-a-workflow_task/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح',
        'menu_name_en' => 'delete Workflow task',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=WorkflowTask&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105224 bfc-',
      ),
      105225 =>
      array(
        'id' => '105225',
        'code' => 'f2-a-workflow_task/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل',
        'menu_name_en' => 'display details of Workflow task',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=WorkflowTask&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105225 bfc-',
      ),
      105226 =>
      array(
        'id' => '105226',
        'code' => 'f2-a-workflow_task/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في workflow_task',
        'menu_name_en' => 'Workflow tasks search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=WorkflowTask&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105226 bfc-',
      ),
      105227 =>
      array(
        'id' => '105227',
        'code' => 'f2-a-workflow_task/qsearch',
        'level' => '999',
        'menu_name_ar' => 'workflow_task',
        'menu_name_en' => 'Workflow tasks',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowTask&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105227 bfc-',
      ),
      105236 =>
      array(
        'id' => '105236',
        'code' => 'f2-a-workflow_transition/edit',
        'level' => '1',
        'menu_name_ar' => 'إنشاء',
        'menu_name_en' => 'create transition',
        'page' => 'main.php?Main_Page=afw_mode_edit.php&cl=WorkflowTransition&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105236 bfc-',
      ),
      105237 =>
      array(
        'id' => '105237',
        'code' => 'f2-a-workflow_transition/qedit',
        'level' => '1',
        'menu_name_ar' => 'إدارة التحولات',
        'menu_name_en' => 'transitions administration',
        'page' => 'main.php?Main_Page=afw_mode_qedit.php&cl=WorkflowTransition&currmod=workflow&ids=all&newo=3',
        'css' => 'bf',
        'icon' => 'bficon-105237 bfc-',
      ),
      105238 =>
      array(
        'id' => '105238',
        'code' => 'f2-a-workflow_transition/delete',
        'level' => '1',
        'menu_name_ar' => 'مسح',
        'menu_name_en' => 'delete transition',
        'page' => 'main.php?Main_Page=afw_mode_delete.php&cl=WorkflowTransition&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105238 bfc-',
      ),
      105239 =>
      array(
        'id' => '105239',
        'code' => 'f2-a-workflow_transition/display',
        'level' => '999',
        'menu_name_ar' => 'عرض تفاصيل',
        'menu_name_en' => 'display details of transition',
        'page' => 'main.php?Main_Page=afw_mode_display.php&cl=WorkflowTransition&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105239 bfc-',
      ),
      105240 =>
      array(
        'id' => '105240',
        'code' => 'f2-a-workflow_transition/search',
        'level' => '1',
        'menu_name_ar' => 'البحث في التحولات',
        'menu_name_en' => 'transitions search',
        'page' => 'main.php?Main_Page=afw_mode_search.php&cl=WorkflowTransition&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105240 bfc-',
      ),
      105241 =>
      array(
        'id' => '105241',
        'code' => 'f2-a-workflow_transition/qsearch',
        'level' => '999',
        'menu_name_ar' => 'التحولات',
        'menu_name_en' => 'transitions',
        'page' => 'main.php?Main_Page=afw_mode_qsearch.php&cl=WorkflowTransition&currmod=workflow',
        'css' => 'bf',
        'icon' => 'bficon-105241 bfc-',
      ),
    ),
    'sub-folders' =>
    array(),
  ),
);
