<?php


class WorkflowWorkflowTransitionAfwStructure
{
    // token separator = §
    public static function initInstance(&$obj)
    {
        if ($obj instanceof WorkflowTransition) {
            $obj->QEDIT_MODE_NEW_OBJECTS_DEFAULT_NUMBER = 15;
            $obj->DISPLAY_FIELD_BY_LANG = ['ar' => "name_ar", 'en' => "name_en"];

            // $obj->ENABLE_DISPLAY_MODE_IN_QEDIT=true;
            $obj->ORDER_BY_FIELDS = "";



            // $obj->UNIQUE_KEY = array('XXX', 'YYY');

            $obj->showQeditErrors = true;
            $obj->showRetrieveErrors = true;
            $obj->general_check_errors = true;
            $obj->after_save_edit = array("class"=>'WorkflowModel',"attribute"=>'workflow_model_id', "currmod"=>'workflow',"currstep"=>2);
            // $obj->after_save_edit = array("mode" => "qsearch", "currmod" => 'workflow', "class" => 'WorkflowTransition', "submit" => true);
        } else {
            WorkflowTransitionArTranslator::initData();
            WorkflowTransitionEnTranslator::initData();
        }
    }


    public static $DB_STRUCTURE =
    array(
        'id' => array('SHOW' => true, 'RETRIEVE' => true, 'EDIT' => false, 'TYPE' => 'PK', 'CSS' => 'width_pct_25',),


        'workflow_module_id' => array(
            'SHORTNAME' => 'module',
            'SEARCH' => true,
            'QSEARCH' => false,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 32,
            'MAXLENGTH' => 32,
            'MIN-SIZE' => 1,
            'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
            'MANDATORY' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'workflow_module',
            'ANSMODULE' => 'workflow',
            'RELATION' => 'ManyToOne',
            'READONLY' => true,
            'DNA' => true,
            'CSS' => 'width_pct_50',
        ),

        'workflow_model_id' => array(
            'SHORTNAME' => 'model',
            'SEARCH' => true,
            'QSEARCH' => false,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 32,
            'MAXLENGTH' => 32,
            'MIN-SIZE' => 1,
            'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
            'MANDATORY' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'workflow_model',
            'ANSMODULE' => 'workflow',
            'RELATION' => 'OneToMany',
            'READONLY' => true,
            'DNA' => true,
            'CSS' => 'width_pct_50',
        ),

        'name_ar' => array(
            'SEARCH' => true,
            'QSEARCH' => true,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 128,
            'MAXLENGTH' => 128,
            'MIN-SIZE' => 5,
            'CHAR_TEMPLATE' => "ARABIC-CHARS,SPACE",
            'MANDATORY' => true,
            'UTF8' => true,
            'TYPE' => 'TEXT',
            'READONLY' => false,
            'CSS' => 'width_pct_50',
        ),

        'name_en' => array(
            'SEARCH' => true,
            'QSEARCH' => true,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 128,
            'MAXLENGTH' => 128,
            'MIN-SIZE' => 5,
            'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
            'MANDATORY' => true,
            'UTF8' => false,
            'TYPE' => 'TEXT',
            'READONLY' => false,
            'DNA' => true,
            'CSS' => 'width_pct_50',
        ),


        'initial_stage_id' => array(
            'SHORTNAME' => 'stage',
            'SEARCH' => true,
            'QSEARCH' => false,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 32,
            'MAXLENGTH' => 32,
            'MIN-SIZE' => 1,
            'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
            'MANDATORY' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'workflow_stage',
            'ANSMODULE' => 'workflow',
            'RELATION' => 'ManyToOne',
            'READONLY' => false,
            'DNA' => true,
            'CSS' => 'width_pct_50',
        ),

        'initial_status_id' => array(
            'SHORTNAME' => 'status',
            'SEARCH' => true,
            'QSEARCH' => false,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'MAXLENGTH' => 32,
            'MIN-SIZE' => 1,
            'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
            'MANDATORY' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'workflow_status',
            'ANSMODULE' => 'workflow',
            'RELATION' => 'ManyToOne',
            'READONLY' => false,
            'DNA' => true,
            'CSS' => 'width_pct_50',
        ),

        'workflow_action_id' => array(
            'SHORTNAME' => 'action',
            'SEARCH' => true,
            'QSEARCH' => false,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'MAXLENGTH' => 32,
            'MIN-SIZE' => 1,
            'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
            'MANDATORY' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'workflow_action',
            'ANSMODULE' => 'workflow',
            'RELATION' => 'ManyToOne',
            'READONLY' => false,
            'DNA' => true,
            'CSS' => 'width_pct_50',
        ),

        'workflow_role_mfk' => array(
            'SHORTNAME' => 'roles',
            'SEARCH' => true,
            'QSEARCH' => false,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => false,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'MAXLENGTH' => 32,
            'MIN-SIZE' => 1,
            'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
            'MANDATORY' => true,
            'UTF8' => false,
            'TYPE' => 'MFK',
            'ANSWER' => 'workflow_role',
            'ANSMODULE' => 'workflow',
            'READONLY' => false,
            'DNA' => true,
            'CSS' => 'width_pct_100',
        ),

        'workflow_condition_id' => array(
            'SHORTNAME' => 'condition',
            'SEARCH' => true,
            'QSEARCH' => false,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'MAXLENGTH' => 32,
            'MIN-SIZE' => 1,
            'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
            'MANDATORY' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'workflow_condition',
            'ANSMODULE' => 'workflow',
            'RELATION' => 'ManyToOne',
            'READONLY' => false,
            'DNA' => true,
            'CSS' => 'width_pct_50',
        ),

        'notification_template_id' => array(
            'SHORTNAME' => 'template',
            'SEARCH' => true,
            'QSEARCH' => false,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'MAXLENGTH' => 32,
            'MIN-SIZE' => 1,
            'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'notification_template',
            'ANSMODULE' => 'workflow',
            'RELATION' => 'ManyToOne',
            'READONLY' => false,
            'DNA' => true,
            'CSS' => 'width_pct_50',
        ),

        'final_stage_id' => array(
            'SHORTNAME' => 'stage',
            'SEARCH' => true,
            'QSEARCH' => false,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => true,
            'SIZE' => 32,
            'MAXLENGTH' => 32,
            'MIN-SIZE' => 1,
            'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
            'MANDATORY' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'workflow_stage',
            'ANSMODULE' => 'workflow',
            'RELATION' => 'ManyToOne',
            'READONLY' => false,
            'DNA' => true,
            'CSS' => 'width_pct_50',
        ),

        'final_status_id' => array(
            'SHORTNAME' => 'status',
            'SEARCH' => true,
            'QSEARCH' => false,
            'SHOW' => true,
            'AUDIT' => false,
            'RETRIEVE' => true,
            'EDIT' => true,
            'QEDIT' => false,
            'SIZE' => 32,
            'MAXLENGTH' => 32,
            'MIN-SIZE' => 1,
            'CHAR_TEMPLATE' => "ALPHABETIC,SPACE",
            'MANDATORY' => true,
            'UTF8' => false,
            'TYPE' => 'FK',
            'ANSWER' => 'workflow_status',
            'ANSMODULE' => 'workflow',
            'RELATION' => 'ManyToOne',
            'READONLY' => false,
            'DNA' => true,
            'CSS' => 'width_pct_50',
        ),


        'created_by'         => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false,  'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'auser', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
        'created_at'         => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'DATETIME', 'FGROUP' => 'tech_fields'),
        'updated_by'         => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'auser', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
        'updated_at'         => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, "TECH_FIELDS-RETRIEVE" => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'DATETIME', 'FGROUP' => 'tech_fields'),
        'validated_by'       => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'auser', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
        'validated_at'       => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'DATETIME', 'FGROUP' => 'tech_fields'),
        'active'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'EDIT' => false, 'QEDIT' => false, "DEFAULT" => 'Y', 'TYPE' => 'YN', 'FGROUP' => 'tech_fields'),
        'version'            => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'INT', 'FGROUP' => 'tech_fields'),
        'draft'             => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'EDIT' => false, 'QEDIT' => false, "DEFAULT" => 'Y', 'TYPE' => 'YN', 'FGROUP' => 'tech_fields'),
        'update_groups_mfk' => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
        'delete_groups_mfk' => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
        'display_groups_mfk' => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'ANSWER' => 'ugroup', 'ANSMODULE' => 'ums', 'TYPE' => 'MFK', 'FGROUP' => 'tech_fields'),
        'sci_id'            => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'SHOW' => true, 'RETRIEVE' => false, 'QEDIT' => false, 'TYPE' => 'FK', 'ANSWER' => 'scenario_item', 'ANSMODULE' => 'ums', 'FGROUP' => 'tech_fields'),
        'tech_notes'           => array('STEP' => 99, 'HIDE_IF_NEW' => true, 'TYPE' => 'TEXT', 'CATEGORY' => 'FORMULA', "SHOW-ADMIN" => true, 'TOKEN_SEP' => "§", 'READONLY' => true, "NO-ERROR-CHECK" => true, 'FGROUP' => 'tech_fields'),
    );
}
